### PR TITLE
 Linear Search in Array 

### PR DESCRIPTION
**Pull request by prajnakalpa**

### CODE REVIEW

**Review by crypticani — COMMENTED** [review]
You said that you are doing it with 2 methods, but both the programs are same.

**Comment by prajnakalpa** [comment]
sorry for the mistake . I uploaded the same file by mistake as the name was
similar to all versions . You can add one of these if you want to ..
Sincere apologies for inconvenience caused .

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Review by crypticani — CHANGES_REQUESTED** [review]
You can upload another file if you want.

**Review by crypticani — APPROVED** [review]
Okay. I am approving your request.
Don't forget to give this repo a star if it increases your PR count in hacktoberfest.

**Comment by prajnakalpa** [comment]
Sure Mate . Good Day .

**Pull request merged**
