### PR TITLE
added file for insertion sort in C language

### PR DESCRIPTION
**Pull request by nishant-08**
Added file for insertion sort algorithm in C language.

### CODE REVIEW

**Review by crypticani — COMMENTED** [review]
Please make the program dynamic (Array should be initialized by taking inputs from user)

**Review by crypticani — CHANGES_REQUESTED** [review]
Please make the program dynamic (Array should be initialized by taking inputs from user)

**Review by crypticani — CHANGES_REQUESTED** [review]
Your program throws an exception. (You are also not defining your typedef variable before using it.)
Here's exception:
[Unknown/Just-In-Time compiled code] (Unknown Source:0)
libc.so.6!__libc_start_main(int (*)(int, char **, char **) main, int argc, char ** argv, int (*)(int, char **, char **) init, void (*)(void) fini, void (*)(void) rtld_fini, void * stack_end) (libc-start.c:308)
_start (Unknown Source:0)


Could not load source './csu/../csu/libc-start.c': 'SourceRequest' not supported..

**Review by crypticani — CHANGES_REQUESTED** [review]
Here's the output of your code in gcc compiler:
image

**Comment by nishant-08** [comment]
> Here's the output of your code in gcc compiler:
> image

Hi. Sorry for the inconvenience. I am getting different (and expected) outputs from online compilers as well as on my PC. Any thoughts?
Screenshot from 2020-10-02 22-01-15
Screenshot from 2020-10-02 22-04-21

**Review by crypticani — COMMENTED** [review]
The problem was in the return statement.
I replaced yours with return 0;
and the program is now working.

**Comment by crypticani** [comment]
Now, you just have to give yourself credits to the program by commenting into it and put the program in the folder named "C Programs/sorting".
If it's done, I will merge the PR.

**Comment by nishant-08** [comment]
> The problem was in the return statement.
> I replaced yours with return 0;
> and the program is now working.
> 

Oh, thank you. I'll look into the problem.

**Comment by crypticani** [comment]
Hey, you forgot to mention your name/username in the program (via commenting).
It would be nice if you comment in your program.

**Review by crypticani — APPROVED** [review]

**Comment by nishant-08** [comment]
> Your program throws an exception. (You are also not defining your typedef variable before using it.)
> Here's exception:
> [Unknown/Just-In-Time compiled code] (Unknown Source:0)
> libc.so.6!__libc_start_main(int (_)(int, char **, char **) main, int argc, char ** argv, int (_)(int, char **, char **) init, void (_)(void) fini, void (_)(void) rtld_fini, void * stack_end) (libc-start.c:308)
> _start (Unknown Source:0)
> 
> Could not load source './csu/../csu/libc-start.c': 'SourceRequest' not supported..

Hi. A follow up on this.
I checked on these issues.

The typedef 'size_t' (which stands for 'unsigned long') is already included in 'stdio.h' and 'stdlib.h' (and some other header files as well). So, I did not define it explicitly in the initial commits.

Also, the macro 'EXIT_SUCCESS' is defined in 'stdlib.h' and almost always has the value 0.

It would be helpful if you could help me with reproducing the error that you came across so that I can look further into it.

**Review by crypticani — COMMENTED** [review]
Sorry for the inconveniences.
I just checked your original program in my compiler (updated today to the latest version) and it's working fine.
I am really sorry that you have to modify your program even if that was correct.
Here's output:
image

**Pull request merged**
